lr_classifier: 7.0e-4
lr_backbone: 2.0e-5
weight_decay_classifier: 0.002
weight_decay_backbone: 0.0001

lr_scheduler:
  T_max: 50        # Usually the total # of epochs
  eta_min: 1.0e-7  # The minimum LR to which we decay

exp_name: "05_small"