lr_classifier: 5.0e-4
lr_backbone: 1.0e-5
weight_decay_classifier: 0.0001
weight_decay_backbone: 0.00001

lr_scheduler:
  T_max: 400        # Usually the total # of epochs
  eta_min: 1.0e-7  # The minimum LR to which we decay

exp_name: "01_debug"

num_classes: 7